id: dify-reset-password

info:
  name: dify-forgot-password
  author: dify
  severity: high
  tags: forgot-password

http:
  - raw:
      - |
        POST /console/api/forgot-password HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
        Content-Type: application/json

        {"email":"test@test123.com","language":"zh-Hans"}
  
    matchers:
      - type: word
        part: body
        words:
          - "code\":\"account_not_found\""
        condition: and
