id: seeyon-oa-config-exposure

info:
  name: Seeyon OA A6 config.jsp - Information Disclosure
  author: seeyon
  severity: medium
  tags: seeyon

http:
  - raw:
      - |
        GET /yyoa/ext/trafaxserver/SystemManage/config.jsp HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DatabaseName="
          - "请在文本框内配置传真插件所需服务器的信息"
        condition: and

      - type: status
        status:
          - 200

# digest: 490a0046304402201c9d8d256dceb74cc016ec7a174967e16ad81a116d43e1ebbb9516370c1e744c022000c6b0aa21015c1255aa0d67740e7fb706295bc5d639d6b65842f1408566e5fd:922c64590222798bb761d5b6d8e72950
