id: seeyon-oa-createmysql-exposure

info:
  name: Seeyon OA A6 createMysql.jsp Database - Information Disclosure
  author: seeyon
  severity: medium
  tags: seeyon,oa,info-leak

http:
  - method: GET
    path:
      - "{{BaseURL}}/yyoa/createMysql.jsp"
      - "{{BaseURL}}/yyoa/ext/createMysql.jsp"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "root</br>"

      - type: regex
        part: body
        regex:
          - "[*][0-zA-Z]{40}</br>"

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100ee9988573daed066e9deadae2dddf213a5fd2325a44738ffc07d7ab96b3bd05102200ec1fe8f49e272746f2100a627d4a08d9a7a556c875629d32b68b86f11314cba:922c64590222798bb761d5b6d8e72950
