id: solr-unauth

info:
  name: Solr Unauth
  author: carrypan
  severity: low
  description: Sensitive environment variables may not be masked
  metadata:
    max-request: 4
  tags: misconfig,solr,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/solr/admin/cores?wt=json&indexInfo=false"
      - "{{BaseURL}}/admin/cores?wt=json&indexInfo=false"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: dsl
        dsl: 
          - 'contains(body, "responseHeader")'
          - 'status_code == 200'
        condition: and

# digest: 490a004630440220047366275efe896f379ed62aa88e8562a4217729eedb6c58246c87966e0efa01022042be407056154a4658d77f95c5cfece9800cc4fc30c35de5bb06dacca8e799a0:922c64590222798bb761d5b6d8e72950
