id: UrlRedirection

info:
  name: UrlRedirection
  author: carrypan
  severity: low

http:
  - method: GET
    path:
      - "{{BaseURL}}/logout?service=https://www.baidu.com"
      - "{{BaseURL}}/cas/logout?service=https://www.baidu.com"
      - "{{BaseURL}}/logout?redirect=https://www.baidu.com"
      - "{{BaseURL}}/https://www.baidu.com/"
      - "{{BaseURL}}//https://www.baidu.com//"
      - "{{BaseURL}}/project/switch/1?targetPath=https://www.baidu.com/"
      - "{{BaseURL}}/getCorsFile?urlPath=https://www.baidu.com"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - 'Location: https://www.baidu.com'

# digest: 4a0a00473045022100d7f4b40014328875952cc9568ed7c755f3fda07d5d70e95b74a713fa717e956b02200be754be20fee807e2cc6be1f55cc3d785a1daab83e7848e218cb4bb3a8e0312:922c64590222798bb761d5b6d8e72950
