id: weblogic-console

info:
  name: Weblogic Console
  author: carrypan
  severity: info
  description: Sensitive environment variables may not be masked
  metadata:
    max-request: 4
  tags: misconfig,weblogic,exposure

http:
  - method: GET
    path:
      - "{{BaseURL}}/#/console/css/test.css"
      - "{{BaseURL}}/#/../console/css/test.css"
      - "{{BaseURL}}/#/../../console/css/test.css"
      - "{{BaseURL}}/console/css/test.css;/../../../"
    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: dsl
        dsl: 
          - 'contains(body, "WLS Administration Console")'
        condition: and

# digest: 490a004630440220047366275efe896f379ed62aa88e8562a4217729eedb6c58246c87966e0efa01022042be407056154a4658d77f95c5cfece9800cc4fc30c35de5bb06dacca8e799a0:922c64590222798bb761d5b6d8e72950
