id: clickhouse-unauth-api

info:
  name: ClickHouse API Database Interface - Improper Authorization
  author: xc
  severity: high
  metadata:
    verified: true
    max-request: 1
    shodan-query: "X-ClickHouse-Summary"
    fofa-query: "X-ClickHouse-Summary"
  tags: clickhouse,unauth,disclosure

http:
  - method: GET
    path:
      - "{{BaseURL}}/?query=SHOW%20DATABASES"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'default'
          - 'system'
        condition: and

      - type: word
        part: header
        words:
          - 'text/tab-separated-values'

      - type: status
        status:
          - 200

# digest: 490a00463044022036599550131f2de458fc72e772f69cae1e3aa73931f856c352ff8ebc85d72ac7022004567b098e2ae9a91cc1f46ed381cb9c41b904d4393b286fbc3cf77bd930d4ae:922c64590222798bb761d5b6d8e72950
