id: netmizer-data-listing

info:
  name: NetMizer LogManagement System Data - Directory Exposure
  author: xc
  severity: high
  description: |
    Directory Exposure vulnerability in the NetMizer log management system of Beijing Lingzhou Network Technology Co., Ltd. Due to the loose control of /data, attackers can use this vulnerability to obtain sensitive information.
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"NetMizer"
    fofa-query: title="NetMizer 日志管理系统"
  tags: netmizer,exposure,listing

http:
  - method: GET
    path:
      - "{{BaseURL}}/data/"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'Index of /data'
          - 'bin/'
        condition: and

      - type: word
        part: header
        words:
          - 'text/html'

      - type: status
        status:
          - 200

# digest: 490a00463044022029b54f7bc9ae216dc0a49bc5f30ee7d384b2298b1c5e38da2f448ab23724449b022005d03b98331ba87169d6d43cd3802e267c323cdd3ba8a712c5ed962ca34eaa6e:922c64590222798bb761d5b6d8e72950
