id: omni-commerce-connect-detect

info:
  name: Omni Commerce Connect (OCC) Rest APIs
  author: xc
  severity: info
  description: The Omni Commerce Connect (OCC) API exposes a broad set of commerce and data services. It enables you to integrate SAP Commerce functionality anywhere in your application landscape.
  metadata:
    verified: true
    max-request: 1
    shodan-query: title:"Hybris"
  tags: tech,sap,hybris,omni

http:
  - method: GET
    path:
      - "{{BaseURL}}/occ/v2/d2OzBcy"

    matchers:
      - type: word
        part: body
        words:
          - "Base site d2OzBcy doesn't exist"

# digest: 4a0a0047304502202e74dc77c3963dc8acb1da0c41ccb61807bdde52b6c58d2453eaa215121a58a0022100e18996fe8ca72258505c73da22b1320c96c0364bf7c4bc8cfb976282224f08cb:922c64590222798bb761d5b6d8e72950
