id: rabbitMQ-rabbitmqadmin-Leak

info:
  name: RabbitMQ rabbitmqadmin Leak
  author: lemonlove7
  severity: medium
  metadata:
    verified: true


http:
  - raw:
      - |-
        GET /cli/rabbitmqadmin HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
        Connection: keep-alive

    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - r_rabbitmqadmin
          - /usr/bin/env
    matchers-condition: and