id: mobotix-default-credentials

info:
  name: Mobotix - Default Login
  author: xc
  severity: high
  description: Mobotix contains a default admin login vulnerability. An attacker can obtain access to user accounts and access sensitive information, modify data, and/or execute unauthorized operations.
  classification:
    cwe-id: CWE-798
  metadata:
    max-request: 2
    shodan-query: title:"Mobotix"
  tags: mobotix,default-login,webcam,iot

http:
  - raw:
      - |
        GET /control/userimage.html HTTP/1.1
        Host: {{Hostname}}
      - |
        GET /control/userimage.html HTTP/1.1
        Host: {{Hostname}}
        Authorization: Basic YWRtaW46bWVpbnNt

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - "!contains(body_1, 'Admin Menu')"
          - 